[package]
name = "qmldemo"
version = "0.1.0"
authors = ["Andreas Pfeil <der.anderas.pfeil@googlemail.com>"]
edition = "2018"

[dependencies]
qmetaobject = "*"
cpp = "*"

[build-dependencies]
cpp_build = "*"

[patch.crates-io]
qmetaobject = { path = "../qmetaobject-rs/qmetaobject" }
